### ISSUE TITLE
Loading page after each "Assign action"

### ISSUE THREAD

**Issue by nayaramoura** [RocketBoard/tablero#133]
For each assign action (assign, cancel assign, unassign...) the application is loading the entire page and it is taking a long time. 

The load should be used just when we need to refresh all the issues (like in the initial access or when we change the repositories selected).

**Comment by nayaramoura** [comment]
Obs.: When this reload happens all the issues are duplicated. So, after each assign action, we have double issues displayed than we have before.

**Comment by rodrigomaia17** [comment]
Fixed! =)
